name: Linting

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install PyTest
      run: |
          pip install -r requirements.txt
          python -m pip install pytest
    - name: Run Unit Tests
      run: | 
        pytest test/
