name: Automatically trigger an Azure Machine Learning job

on:
  push:
    branches:
      - main
      
jobs:
  train-model:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group='rg-dev-mlops' 
        az configure --defaults workspace='mlw-dev-mlops' 
    - name: Train an Azure Machine Learning job
      run: |
        cd src
        az ml job create --file job.yml --stream
        # RUN_ID=$(az ml job create --file job.yml --stream --query name -o tsv)
        # RUN_ID=$(az ml job create --file job.yml --stream --query RunId)  
        # az ml model create --name diabetes-model --version 1 --path runs:/$RUN_ID/model/ --type mlflow_model
    - name: Register the model in the registry
      run:  |
          JOB_NAME=$(az ml job list --query "[0].name" | tr -d '"')
          az ml model create --name "diabetes-model" \
                   --type "mlflow_model" \
                   --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"    

  deploy-model:
    runs-on: ubuntu-latest
    environment: production
    needs: train-model
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group='rg-dev-mlops' 
        az configure --defaults workspace='mlw-dev-mlops' 
    - name: Deploy Model
      run: |
        az ml model list


